### ISSUE TITLE
do the dataprocess

### ISSUE THREAD

**Issue by dj1367250510** [NOrangeeroli/SecondPose#3]
when i  run the  data_processing  of  self-dpdn  first,then i run the data_processs of secondpose  second,then i meet this problem!can you give me some help?where the detection  i can download?
![image](https://github.com/NOrangeeroli/SecondPose/assets/74551357/9d8aa418-3a0e-4ca0-a36d-e7d8387063a7)

**Comment by NOrangeeroli** [comment]
Hi, The detection folder is just the segmentation results. I suggest to add a soft link in the data folder from the folder segmentation_results to detection.

**Comment by jhqwdk** [comment]
hello!when i start train,i alwalys meet the problem like this:

**Comment by dj1367250510** [comment]
> Hi, The detection folder is just the segmentation results. I suggest to add a soft link in the data folder from the folder segmentation_results to detection.

hello,When I start training, I always encounter the following problems：
Epoch 1 :
2024-01-02 10:11:41,480 - [1/60][0/4999][0] Train - loss: 17.91323      vp_loss: 0.17252  ip_loss: 0.66172  rho_acc: 0.00000  phi_acc: 2.08333residual_angle_loss: 124.16344  5d_loss: 0.00000  lr: 0.000001      T_data: 11.999    T_forward: 5.742  T_backward: 0.558 
2024-01-02 10:12:11,450 - [1/60][50/4999][50] Train - loss: 15.46198    vp_loss: 0.14857  ip_loss: 0.60527  rho_acc: 4.00000  phi_acc: 5.25000residual_angle_loss: 111.86561  5d_loss: 0.00000  lr: 0.000014      T_data: 0.074     T_forward: 0.283  T_backward: 0.241 
2024-01-02 10:12:47,679 - [1/60][100/4999][100] Train - loss: 8.56143   vp_loss: 0.08075  ip_loss: 0.48615  rho_acc: 6.54167  phi_acc: 6.41667residual_angle_loss: 86.32484   5d_loss: 0.00000  lr: 0.000039      T_data: 0.170     T_forward: 0.314  T_backward: 0.240 
2024-01-02 10:13:27,278 - [1/60][150/4999][150] Train - loss: 4.74307   vp_loss: 0.04347  ip_loss: 0.39627  rho_acc: 10.16667 phi_acc: 8.66667residual_angle_loss: 69.64372   5d_loss: 0.00208  lr: 0.000064      T_data: 0.239     T_forward: 0.308  T_backward: 0.244 
libpng error: Read Error
[ WARN:0@254.121] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/media/ailab/DJ/data/camera/train/01215/0005_depth.png'): can't open/read file: check file path/integrity
[ WARN:0@254.121] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/media/ailab/DJ/data/camera/train/05483/0004_depth.png'): can't open/read file: check file path/integrity
[ WARN:0@254.121] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/media/ailab/DJ/data/camera/train/06223/0002_color.png'): can't open/read file: check file path/integrity
[ WARN:0@254.122] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/media/ailab/DJ/data/real/train/scene_1/0520_depth.png'): can't open/read file: check file path/integrity
[ WARN:0@254.123] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/media/ailab/DJ/data/camera/train/22504/0006_depth.png'): can't open/read file: check file path/integrity
[ WARN:0@254.123] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/media/ailab/DJ/data/camera/train/16628/0009_depth.png'): can't open/read file: check file path/integrity
[ WARN:0@254.124] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/media/ailab/DJ/data/camera/train/25396/0008_depth.png'): can't open/read file: check file path/integrity
[ WARN:0@254.124] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/media/ailab/DJ/data/camera/train/04380/0001_depth.png'): can't open/read file: check file path/integrity
[ WARN:0@254.124] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/media/ailab/DJ/data/camera/train/12581/0008_depth.png'): can't open/read file: check file path/integrity
[ WARN:0@254.124] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/media/ailab/DJ/data/real/train/scene_4/0440_depth.png'): can't open/read file: check file path/integrity
[ WARN:0@254.124] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/media/ailab/DJ/data/camera/train/05071/0009_depth.png'): can't open/read file: check file path/integrity
[ WARN:0@254.124] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/media/ailab/DJ/data/camera/train/21895/0002_depth.png'): can't open/read file: check file path/integrity
[ WARN:0@254.124] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/media/ailab/DJ/data/camera/train/25711/0006_depth.png'): can't open/read file: check file path/integrity
[ WARN:0@254.124] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/media/ailab/DJ/data/camera/train/19343/0000_depth.png'): can't open/read file: check file path/integrity
[ WARN:0@254.124] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/media/ailab/DJ/data/camera/train/16666/0002_depth.png'): can't open/read file: check file path/integrity
[ WARN:0@254.125] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/media/ailab/DJ/data/camera/train/16102/0006_depth.png'): can't open/read file: check file path/integrity
[ WARN:0@254.126] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/media/ailab/DJ/data/camera/train/04881/0007_depth.png'): can't open/read file: check file path/integrity
[ WARN:0@254.127] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/media/ailab/DJ/data/camera/train/10406/0008_depth.png'): can't open/read file: check file path/integrity
[ WARN:0@254.127] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/media/ailab/DJ/data/real/train/scene_4/0485_depth.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "/data2/dj/SecondPose-main/train_geodino.py", line 142, in <module>
    Trainer.solve()
  File "/data2/dj/SecondPose-main/utils/solver_category.py", line 50, in solve
    dict_info_train = self.train()
  File "/data2/dj/SecondPose-main/utils/solver_category.py", line 76, in train
    for i, data in enumerate(self.dataloaders["train"]):
  File "/home/ailab/anaconda3/envs/Secpose/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/ailab/anaconda3/envs/Secpose/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/ailab/anaconda3/envs/Secpose/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/ailab/anaconda3/envs/Secpose/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ailab/anaconda3/envs/Secpose/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ailab/anaconda3/envs/Secpose/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ailab/anaconda3/envs/Secpose/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data2/dj/SecondPose-main/provider/dataset_category.py", line 274, in __getitem__
    data_dict = self._read_instance_cat(index, cat)
  File "/data2/dj/SecondPose-main/provider/dataset_category.py", line 296, in _read_instance_cat
    tuple = get_data(index)
  File "/data2/dj/SecondPose-main/provider/dataset_category.py", line 293, in get_data
    return self._load_data(img_path,
  File "/data2/dj/SecondPose-main/provider/dataset_category.py", line 473, in _load_data
    depth = load_composed_depth(img_path)
  File "/data2/dj/SecondPose-main/utils/data_utils.py", line 32, in load_composed_depth
    if len(depth.shape) == 3:
AttributeError: 'NoneType' object has no attribute 'shape'

I can guarantee that my data set is fine, I have completed some preparatory work, can you give me guidance？

**Comment by NOrangeeroli** [comment]
That's quite strange error, it seems to be a problem with the data folder, not related to this repository. The same dataset is also used in VI-Net(https://github.com/JiehongLin/VI-Net) I would suggest to try running the code of VI-Net to check if the error is still there. If that's the case your might need to check what's wrong with your data folder.(possibly some files are damaged?)

**Comment by dj1367250510** [comment]
@NOrangeeroli 
Thank you for your previous explanation, I'm sorry to bother you again, I want to ask where the file in the picture below is, can you provide the .npy file？
![M OHJT5YNL8GV_Q4 NMHVTW](https://github.com/NOrangeeroli/SecondPose/assets/74551357/2aefbea5-aa58-44dc-bb3b-c51313b9bdf8)

**Comment by NOrangeeroli** [comment]
> @NOrangeeroli Thank you for your previous explanation, I'm sorry to bother you again, I want to ask where the file in the picture below is, can you provide the .npy file？ ![M OHJT5YNL8GV_Q4 NMHVTW](https://private-user-images.githubusercontent.com/74551357/295216293-2aefbea5-aa58-44dc-bb3b-c51313b9bdf8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MTE1OTMsIm5iZiI6MTcwNDkxMTI5MywicGF0aCI6Ii83NDU1MTM1Ny8yOTUyMTYyOTMtMmFlZmJlYTUtYWE1OC00NGRjLWJiM2ItYzUxMzEzYjliZGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDE4MjgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNWI1MjA5YTEwMmY1OWI2NTM0N2E5YmYwNjIwMzQ5ZmRlNzc0ZWU5MzkwNjEyYzcxYjY0OTU0NWM0MjhjNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6yPpq-lQdZ1LyNR3W_2f0633Ynyx4Xjb_m5ACtCg6Zc)

Hi,
Thanks for pointing out the issue, that file is no longer needed for current version of our code. I've cleaned it. Please check out the latest code. Sorry for the inconvenience!

Best,
Yamei
