### ISSUE TITLE
ImportError from sphericalmap_utils

### ISSUE THREAD

**Issue by ji-min-song** [NOrangeeroli/SecondPose#8]
I setup my environment with python 3.9, pytorch 1.13.0 and xformers==0.0.12 (0.0.16 required pytorch 1.13.1)

When i run `python train_geodino.py --gpus 0 --mod r`, below error is occurred.

```
set CUDA_VISIBLE_DEVICES as 0
2024-07-07 21:10:50,349 - ************************ Start Logging ************************
2024-07-07 21:10:50,349 - Config (path: config/base.yaml)
{
    "rd_seed": 1,
    "n_cls": 6,
    "resolution": 64,
    "ds_rate": 2,
    "mode": "epoch",
    "max_epoch": 60,
    "num_mini_batch_per_epoch": 5000,
    "num_patches": 15,
    "optimizer": {
        "type": "Adam",
        "lr": 0.001,
        "betas": [
            0.5,
            0.999
        ],
        "eps": 1e-06,
        "weight_decay": 0
    },
    "lr_scheduler": {
        "type": "WarmupCosineLR",
        "max_iters": 200000,
        "warmup_factor": 0.001,
        "warmup_iters": 2000
    },
    "loss": {
        "vp_weight": 100.0,
        "t_weight": 1.0,
        "s_weight": 1.0
    },
    "train_dataset": {
        "data_dir": "../../data/NOCS",
        "sample_num": 2048,
        "random_rotate": true,
        "angle_range": 20
    },
    "train_dataloader": {
        "bs": 48,
        "num_workers": 16,
        "shuffle": true,
        "drop_last": true,
        "pin_memory": false
    },
    "test": {
        "sample_num": 2048,
        "data_dir": "../../data/NOCS"
    },
    "per_val": 10,
    "per_write": 50,
    "dataset": "REAL275",
    "mod": "r",
    "gpus": "0",
    "checkpoint_epoch": -1,
    "log_dir": "log/REAL275/VI_Net_geodino"
}
2024-07-07 21:10:50,352 - using gpu: 0
2024-07-07 21:10:50,353 - => creating model ...
Traceback (most recent call last):
  File "/hdd1/SecondPose/train_geodino.py", line 95, in <module>
    from VI_Net_geodino import Net, Loss
  File "/hdd1/SecondPose/model/VI_Net_geodino.py", line 10, in <module>
    from smap_utils import Feat2Smap
  File "/hdd1/SecondPose/lib/sphericalmap_utils/smap_utils.py", line 14, in <module>
    import spherical._ext as _ext
ImportError: /home/song/.conda/envs/secondpose/lib/python3.9/site-packages/spherical/_ext.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE
```

Can I get some advice for this error?

**Comment by NOrangeeroli** [comment]
Hi, did you setup the environment following the instructions in the readme file?

**Comment by ji-min-song** [comment]
Yes, i did. But i met this problem. Could you offer to us the environment by docker image? If the situation isn't favorable, please let me know. It seems there might be version conflicts with other packages, so I'll keep trying. :)
